/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.core.registries.Registries
 *  net.minecraft.network.chat.Component
 *  net.minecraft.resources.ResourceKey
 *  net.minecraft.resources.ResourceLocation
 *  net.minecraft.world.item.CreativeModeTab
 *  net.minecraft.world.item.Item
 *  net.minecraft.world.item.ItemStack
 *  net.minecraft.world.level.ItemLike
 *  net.minecraftforge.registries.DeferredRegister
 *  net.minecraftforge.registries.ForgeRegistries
 *  net.minecraftforge.registries.IForgeRegistry
 *  net.minecraftforge.registries.RegistryObject
 */
package com.manbo.v2c;

import com.manbo.v2c.ModBlocks;
import com.manbo.v2c.item.equipments.HajimiBoots;
import com.manbo.v2c.item.equipments.HajimiChestplate;
import com.manbo.v2c.item.equipments.HajimiHelmet;
import com.manbo.v2c.item.equipments.HajimiLeggings;
import com.manbo.v2c.item.equipments.KingsShadow;
import com.manbo.v2c.item.equipments.ManboInfinityAlepbBoots;
import com.manbo.v2c.item.equipments.ManboInfinityAlepbChestplate;
import com.manbo.v2c.item.equipments.ManboInfinityAlepbHelmet;
import com.manbo.v2c.item.equipments.ManboInfinityAlepbLeggings;
import com.manbo.v2c.item.equipments.ManboInfinityGoldenBoots;
import com.manbo.v2c.item.equipments.ManboInfinityGoldenChestplate;
import com.manbo.v2c.item.equipments.ManboInfinityGoldenHelmet;
import com.manbo.v2c.item.equipments.ManboInfinityGoldenLeggings;
import com.manbo.v2c.item.equipments.ManboInfinityUnknownBoots;
import com.manbo.v2c.item.equipments.ManboInfinityUnknownChestplate;
import com.manbo.v2c.item.equipments.ManboInfinityUnknownHelmet;
import com.manbo.v2c.item.equipments.ManboInfinityUnknownLeggings;
import com.manbo.v2c.item.equipments.ManboInfinityUpgradeBoots;
import com.manbo.v2c.item.equipments.ManboInfinityUpgradeChestplate;
import com.manbo.v2c.item.equipments.ManboInfinityUpgradeHelmet;
import com.manbo.v2c.item.equipments.ManboInfinityUpgradeLeggings;
import com.manbo.v2c.item.equipments.NanbeilvdouBoots;
import com.manbo.v2c.item.equipments.NanbeilvdouChestplate;
import com.manbo.v2c.item.equipments.NanbeilvdouHelmet;
import com.manbo.v2c.item.equipments.NanbeilvdouLeggings;
import com.manbo.v2c.item.equipments.ShuangshengBoots;
import com.manbo.v2c.item.equipments.ShuangshengChestplate;
import com.manbo.v2c.item.equipments.ShuangshengHelmet;
import com.manbo.v2c.item.equipments.ShuangshengLeggings;
import com.manbo.v2c.item.equipments.TianyuanBoots;
import com.manbo.v2c.item.equipments.TianyuanChestplate;
import com.manbo.v2c.item.equipments.TianyuanHelmet;
import com.manbo.v2c.item.equipments.TianyuanLeggings;
import com.manbo.v2c.item.foods.RoastedHorseshoe;
import com.manbo.v2c.item.materials.DatianCoreJuex;
import com.manbo.v2c.item.materials.FinalHajimi;
import com.manbo.v2c.item.materials.FinalManbo;
import com.manbo.v2c.item.materials.HajimiCore;
import com.manbo.v2c.item.materials.HajimiFeet;
import com.manbo.v2c.item.materials.HajimiTianyuanOrb;
import com.manbo.v2c.item.materials.HajimiTianyuanUn;
import com.manbo.v2c.item.materials.ManboAlephCore;
import com.manbo.v2c.item.materials.ManboBeyondCore;
import com.manbo.v2c.item.materials.ManboCore;
import com.manbo.v2c.item.materials.ManboFeet;
import com.manbo.v2c.item.materials.ManboGoldenHourCore;
import com.manbo.v2c.item.materials.ManboInfinityCore;
import com.manbo.v2c.item.materials.ManboInvisableCore;
import com.manbo.v2c.item.materials.ManboUnknownCore;
import com.manbo.v2c.item.materials.ManboUpgradeCore;
import com.manbo.v2c.item.materials.ManboUpgradeInfinityCore;
import com.manbo.v2c.item.materials.ManboVoidCore;
import com.manbo.v2c.item.materials.NanbeilvdouCore;
import com.manbo.v2c.item.materials.ShuangshengCore;
import com.manbo.v2c.item.materials.TianyuanCoreJuex;
import com.manbo.v2c.item.materials.UniverseShard;
import com.manbo.v2c.item.materials.Zero;
import com.manbo.v2c.item.weapons.HajimiStick;
import com.manbo.v2c.item.weapons.ManboBasicSword;
import com.manbo.v2c.item.weapons.ManboFinalSword;
import com.manbo.v2c.item.weapons.ManboPickaxeBegin;
import com.manbo.v2c.item.weapons.ManboPickaxeSuper;
import com.manbo.v2c.item.weapons.ManboPickaxeUpgrade;
import com.manbo.v2c.item.weapons.ManboStick;
import com.manbo.v2c.item.weapons.ManboSword;
import com.manbo.v2c.item.weapons.ManboVoidSword;
import com.manbo.v2c.item.weapons.ManbohajimiSuperSword;
import com.manbo.v2c.item.weapons.Piggod;
import com.manbo.v2c.item.weapons.ShuangshengMati;
import com.manbo.v2c.item.weapons.ShuangshengSword;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ItemLike;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.RegistryObject;

public class ModItems {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create((IForgeRegistry)ForgeRegistries.ITEMS, (String)"manbov2c");
    public static final RegistryObject<Item> MANBO_BASIC_SWORD = ITEMS.register("manbo_basic_sword", () -> new ManboBasicSword());
    public static final RegistryObject<Item> MANBO_CORE = ITEMS.register("manbo_core", () -> new ManboCore());
    public static final RegistryObject<Item> HAJIMI_CORE = ITEMS.register("hajimi_core", () -> new HajimiCore());
    public static final RegistryObject<Item> HAJIMI_STICK = ITEMS.register("hajimi_stick", () -> new HajimiStick());
    public static final RegistryObject<Item> MANBO_STICK = ITEMS.register("manbo_stick", () -> new ManboStick());
    public static final RegistryObject<Item> MANBO_SWORD = ITEMS.register("manbo_sword", () -> new ManboSword());
    public static final RegistryObject<Item> PIGGOD = ITEMS.register("piggod", () -> new Piggod());
    public static final RegistryObject<Item> MANBO_FEET = ITEMS.register("manbo_feet", () -> new ManboFeet());
    public static final RegistryObject<Item> MANBO_VOID_CORE = ITEMS.register("manbo_void_core", () -> new ManboVoidCore());
    public static final RegistryObject<Item> HAJIMI_HELMET = ITEMS.register("hajimi_helmet", () -> new HajimiHelmet());
    public static final RegistryObject<Item> HAJIMI_CHESTPLATE = ITEMS.register("hajimi_chestplate", () -> new HajimiChestplate());
    public static final RegistryObject<Item> HAJIMI_LEGGINGS = ITEMS.register("hajimi_leggings", () -> new HajimiLeggings());
    public static final RegistryObject<Item> HAJIMI_BOOTS = ITEMS.register("hajimi_boots", () -> new HajimiBoots());
    public static final RegistryObject<Item> MANBO_UPGRADE_CORE = ITEMS.register("manbo_upgrade_core", () -> new ManboUpgradeCore());
    public static final RegistryObject<Item> NANBEILVDOU_HELMET = ITEMS.register("nanbeilvdou_helmet", () -> new NanbeilvdouHelmet());
    public static final RegistryObject<Item> NANBEILVDOU_CHESTPLATE = ITEMS.register("nanbeilvdou_chestplate", () -> new NanbeilvdouChestplate());
    public static final RegistryObject<Item> NANBEILVDOU_LEGGINGS = ITEMS.register("nanbeilvdou_leggings", () -> new NanbeilvdouLeggings());
    public static final RegistryObject<Item> NANBEILVDOU_BOOTS = ITEMS.register("nanbeilvdou_boots", () -> new NanbeilvdouBoots());
    public static final RegistryObject<Item> NANBEILVDOU_CORE = ITEMS.register("nanbeilvdou_core", () -> new NanbeilvdouCore());
    public static final RegistryObject<Item> TIANYUAN_HELMET = ITEMS.register("tianyuan_helmet", () -> new TianyuanHelmet());
    public static final RegistryObject<Item> TIANYUAN_CHESTPLATE = ITEMS.register("tianyuan_chestplate", () -> new TianyuanChestplate());
    public static final RegistryObject<Item> TIANYUAN_LEGGINGS = ITEMS.register("tianyuan_leggings", () -> new TianyuanLeggings());
    public static final RegistryObject<Item> TIANYUAN_BOOTS = ITEMS.register("tianyuan_boots", () -> new TianyuanBoots());
    public static final RegistryObject<Item> HAJIMI_TIANYUAN_ORB = ITEMS.register("hajimi_tianyuan_orb", () -> new HajimiTianyuanOrb());
    public static final RegistryObject<Item> SHUANGSHENG_MATI = ITEMS.register("shuangsheng_mati", () -> new ShuangshengMati());
    public static final RegistryObject<Item> SHUANGSHENG_CORE = ITEMS.register("shuangsheng_core", () -> new ShuangshengCore());
    public static final RegistryObject<Item> SHUANGSHENG_HELMET = ITEMS.register("shuangsheng_helmet", () -> new ShuangshengHelmet());
    public static final RegistryObject<Item> SHUANGSHENG_CHESTPLATE = ITEMS.register("shuangsheng_chestplate", () -> new ShuangshengChestplate());
    public static final RegistryObject<Item> SHUANGSHENG_LEGGINGS = ITEMS.register("shuangsheng_leggings", () -> new ShuangshengLeggings());
    public static final RegistryObject<Item> SHUANGSHENG_BOOTS = ITEMS.register("shuangsheng_boots", () -> new ShuangshengBoots());
    public static final RegistryObject<Item> SHUANGSHENG_SWORD = ITEMS.register("shuangsheng_sword", () -> new ShuangshengSword());
    public static final RegistryObject<Item> MANBO_PICKAXE_BEGIN = ITEMS.register("manbo_pickaxe_begin", () -> new ManboPickaxeBegin());
    public static final RegistryObject<Item> MANBO_PICKAXE_SUPER = ITEMS.register("manbo_pickaxe_super", () -> new ManboPickaxeSuper());
    public static final RegistryObject<Item> MANBO_PICKAXE_UPGRADE = ITEMS.register("manbo_pickaxe_upgrade", () -> new ManboPickaxeUpgrade());
    public static final RegistryObject<Item> ROASTED_HORSESHOE = ITEMS.register("roasted_horseshoe", () -> new RoastedHorseshoe());
    public static final RegistryObject<Item> MANBO_VOID_SWORD = ITEMS.register("manbo_void_sword", () -> new ManboVoidSword());
    public static final RegistryObject<Item> MANBOHAJIMI_SUPER_SWORD = ITEMS.register("manbohajimi_super_sword", () -> new ManbohajimiSuperSword());
    public static final RegistryObject<Item> HAJIMI_TIANYUAN_UN = ITEMS.register("hajimi_tianyuan_un", () -> new HajimiTianyuanUn());
    public static final RegistryObject<Item> TIANYUAN_CORE_JUEX = ITEMS.register("tianyuan_core_juex", () -> new TianyuanCoreJuex());
    public static final RegistryObject<Item> DATIAN_CORE_JUEX = ITEMS.register("datian_core_juex", () -> new DatianCoreJuex());
    public static final RegistryObject<Item> HAJIMI_FEET = ITEMS.register("hajimi_feet", () -> new HajimiFeet());
    public static final RegistryObject<Item> MANBO_INFINITY_CORE = ITEMS.register("manbo_infinity_core", () -> new ManboInfinityCore());
    public static final RegistryObject<Item> MANBO_BEYOND_CORE = ITEMS.register("manbo_beyond_core", () -> new ManboBeyondCore());
    public static final RegistryObject<Item> MANBO_INVISABLE_CORE = ITEMS.register("manbo_invisable_core", () -> new ManboInvisableCore());
    public static final RegistryObject<Item> UNIVERSE_SHARD = ITEMS.register("universe_shard", () -> new UniverseShard());
    public static final RegistryObject<Item> MANBO_UPGRADE_INFINITY_CORE = ITEMS.register("manbo_upgrade_infinity_core", () -> new ManboUpgradeInfinityCore());
    public static final RegistryObject<Item> MANBO_GOLDENHOUR_CORE = ITEMS.register("manbo_goldenhour_core", () -> new ManboGoldenHourCore());
    public static final RegistryObject<Item> MANBO_ALEPB_CORE = ITEMS.register("manbo_alepb_core", () -> new ManboAlephCore());
    public static final RegistryObject<Item> MANBO_UNKNOWN_CORE = ITEMS.register("manbo_unknown_core", () -> new ManboUnknownCore());
    public static final RegistryObject<Item> ZERO = ITEMS.register("zero", () -> new Zero());
    public static final RegistryObject<Item> FINAL_MANBO = ITEMS.register("final_manbo", () -> new FinalManbo());
    public static final RegistryObject<Item> FINAL_HAJIMI = ITEMS.register("final_hajimi", () -> new FinalHajimi());
    public static final RegistryObject<Item> MANBO_INFINITY_UPGRADE_HELMET = ITEMS.register("manbo_infinity_upgrade_helmet", () -> new ManboInfinityUpgradeHelmet());
    public static final RegistryObject<Item> MANBO_INFINITY_UPGRADE_CHESTPLATE = ITEMS.register("manbo_infinity_upgrade_chestplate", () -> new ManboInfinityUpgradeChestplate());
    public static final RegistryObject<Item> MANBO_INFINITY_UPGRADE_LEGGINGS = ITEMS.register("manbo_infinity_upgrade_leggings", () -> new ManboInfinityUpgradeLeggings());
    public static final RegistryObject<Item> MANBO_INFINITY_UPGRADE_BOOTS = ITEMS.register("manbo_infinity_upgrade_boots", () -> new ManboInfinityUpgradeBoots());
    public static final RegistryObject<Item> MANBO_INFINITY_GOLDEN_HELMET = ITEMS.register("manbo_infinity_golden_helmet", () -> new ManboInfinityGoldenHelmet());
    public static final RegistryObject<Item> MANBO_INFINITY_GOLDEN_CHESTPLATE = ITEMS.register("manbo_infinity_golden_chestplate", () -> new ManboInfinityGoldenChestplate());
    public static final RegistryObject<Item> MANBO_INFINITY_GOLDEN_LEGGINGS = ITEMS.register("manbo_infinity_golden_leggings", () -> new ManboInfinityGoldenLeggings());
    public static final RegistryObject<Item> MANBO_INFINITY_GOLDEN_BOOTS = ITEMS.register("manbo_infinity_golden_boots", () -> new ManboInfinityGoldenBoots());
    public static final RegistryObject<Item> MANBO_INFINITY_ALEPB_HELMET = ITEMS.register("manbo_infinity_alepb_helmet", () -> new ManboInfinityAlepbHelmet());
    public static final RegistryObject<Item> MANBO_INFINITY_ALEPB_CHESTPLATE = ITEMS.register("manbo_infinity_alepb_chestplate", () -> new ManboInfinityAlepbChestplate());
    public static final RegistryObject<Item> MANBO_INFINITY_ALEPB_LEGGINGS = ITEMS.register("manbo_infinity_alepb_leggings", () -> new ManboInfinityAlepbLeggings());
    public static final RegistryObject<Item> MANBO_INFINITY_ALEPB_BOOTS = ITEMS.register("manbo_infinity_alepb_boots", () -> new ManboInfinityAlepbBoots());
    public static final RegistryObject<Item> MANBO_INFINITY_UNKNOWN_HELMET = ITEMS.register("manbo_infinity_unknown_helmet", () -> new ManboInfinityUnknownHelmet());
    public static final RegistryObject<Item> MANBO_INFINITY_UNKNOWN_CHESTPLATE = ITEMS.register("manbo_infinity_unknown_chestplate", () -> new ManboInfinityUnknownChestplate());
    public static final RegistryObject<Item> MANBO_INFINITY_UNKNOWN_LEGGINGS = ITEMS.register("manbo_infinity_unknown_leggings", () -> new ManboInfinityUnknownLeggings());
    public static final RegistryObject<Item> MANBO_INFINITY_UNKNOWN_BOOTS = ITEMS.register("manbo_infinity_unknown_boots", () -> new ManboInfinityUnknownBoots());
    public static final RegistryObject<Item> KINGS_SHADOW = ITEMS.register("kings_shadow", () -> new KingsShadow());
    public static final RegistryObject<Item> MANBO_FINAL_SWORD = ITEMS.register("manbo_final_sword", () -> new ManboFinalSword());
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create((ResourceKey)Registries.CREATIVE_MODE_TAB, (String)"manbov2c");
    public static final RegistryObject<CreativeModeTab> MANBO_TAB = TABS.register("manbo_tab", () -> CreativeModeTab.builder().title((Component)Component.translatable((String)"creativetab.manbov2c")).icon(() -> new ItemStack((ItemLike)MANBO_BASIC_SWORD.get())).withBackgroundLocation(new ResourceLocation("manbov2c", "textures/gui/container/creative_inventory/tab_manbo_tab.png")).displayItems((params, output) -> {
        output.accept((ItemLike)MANBO_BASIC_SWORD.get());
        output.accept((ItemLike)MANBO_CORE.get());
        output.accept((ItemLike)HAJIMI_CORE.get());
        output.accept((ItemLike)HAJIMI_STICK.get());
        output.accept((ItemLike)MANBO_STICK.get());
        output.accept((ItemLike)MANBO_SWORD.get());
        output.accept((ItemLike)PIGGOD.get());
        output.accept((ItemLike)MANBO_FEET.get());
        output.accept((ItemLike)MANBO_VOID_CORE.get());
        output.accept((ItemLike)HAJIMI_HELMET.get());
        output.accept((ItemLike)HAJIMI_CHESTPLATE.get());
        output.accept((ItemLike)HAJIMI_LEGGINGS.get());
        output.accept((ItemLike)HAJIMI_BOOTS.get());
        output.accept((ItemLike)MANBO_UPGRADE_CORE.get());
        output.accept((ItemLike)NANBEILVDOU_HELMET.get());
        output.accept((ItemLike)NANBEILVDOU_CHESTPLATE.get());
        output.accept((ItemLike)NANBEILVDOU_LEGGINGS.get());
        output.accept((ItemLike)NANBEILVDOU_BOOTS.get());
        output.accept((ItemLike)NANBEILVDOU_CORE.get());
        output.accept((ItemLike)TIANYUAN_HELMET.get());
        output.accept((ItemLike)TIANYUAN_CHESTPLATE.get());
        output.accept((ItemLike)TIANYUAN_LEGGINGS.get());
        output.accept((ItemLike)TIANYUAN_BOOTS.get());
        output.accept((ItemLike)HAJIMI_TIANYUAN_ORB.get());
        output.accept((ItemLike)SHUANGSHENG_MATI.get());
        output.accept((ItemLike)SHUANGSHENG_CORE.get());
        output.accept((ItemLike)SHUANGSHENG_HELMET.get());
        output.accept((ItemLike)SHUANGSHENG_CHESTPLATE.get());
        output.accept((ItemLike)SHUANGSHENG_LEGGINGS.get());
        output.accept((ItemLike)SHUANGSHENG_BOOTS.get());
        output.accept((ItemLike)SHUANGSHENG_SWORD.get());
        output.accept((ItemLike)MANBO_PICKAXE_BEGIN.get());
        output.accept((ItemLike)MANBO_PICKAXE_SUPER.get());
        output.accept((ItemLike)MANBO_PICKAXE_UPGRADE.get());
        output.accept((ItemLike)ROASTED_HORSESHOE.get());
        output.accept((ItemLike)MANBO_VOID_SWORD.get());
        output.accept((ItemLike)MANBOHAJIMI_SUPER_SWORD.get());
        output.accept((ItemLike)HAJIMI_TIANYUAN_UN.get());
        output.accept((ItemLike)TIANYUAN_CORE_JUEX.get());
        output.accept((ItemLike)DATIAN_CORE_JUEX.get());
        output.accept((ItemLike)HAJIMI_FEET.get());
        output.accept((ItemLike)MANBO_INFINITY_CORE.get());
        output.accept((ItemLike)UNIVERSE_SHARD.get());
        output.accept((ItemLike)MANBO_UPGRADE_INFINITY_CORE.get());
        output.accept((ItemLike)MANBO_GOLDENHOUR_CORE.get());
        output.accept((ItemLike)MANBO_ALEPB_CORE.get());
        output.accept((ItemLike)MANBO_UNKNOWN_CORE.get());
        output.accept((ItemLike)ZERO.get());
        output.accept((ItemLike)FINAL_MANBO.get());
        output.accept((ItemLike)FINAL_HAJIMI.get());
        output.accept((ItemLike)MANBO_INFINITY_UPGRADE_HELMET.get());
        output.accept((ItemLike)MANBO_INFINITY_UPGRADE_CHESTPLATE.get());
        output.accept((ItemLike)MANBO_INFINITY_UPGRADE_LEGGINGS.get());
        output.accept((ItemLike)MANBO_INFINITY_UPGRADE_BOOTS.get());
        output.accept((ItemLike)MANBO_INFINITY_GOLDEN_HELMET.get());
        output.accept((ItemLike)MANBO_INFINITY_GOLDEN_CHESTPLATE.get());
        output.accept((ItemLike)MANBO_INFINITY_GOLDEN_LEGGINGS.get());
        output.accept((ItemLike)MANBO_INFINITY_GOLDEN_BOOTS.get());
        output.accept((ItemLike)MANBO_INFINITY_ALEPB_HELMET.get());
        output.accept((ItemLike)MANBO_INFINITY_ALEPB_CHESTPLATE.get());
        output.accept((ItemLike)MANBO_INFINITY_ALEPB_LEGGINGS.get());
        output.accept((ItemLike)MANBO_INFINITY_ALEPB_BOOTS.get());
        output.accept((ItemLike)MANBO_INFINITY_UNKNOWN_HELMET.get());
        output.accept((ItemLike)MANBO_INFINITY_UNKNOWN_CHESTPLATE.get());
        output.accept((ItemLike)MANBO_INFINITY_UNKNOWN_LEGGINGS.get());
        output.accept((ItemLike)MANBO_INFINITY_UNKNOWN_BOOTS.get());
        output.accept((ItemLike)ModBlocks.TIANYUAN_BLOCK_UN_ITEM.get());
        output.accept((ItemLike)ModBlocks.TIANYUAN_BLOCK_ITEM.get());
        output.accept((ItemLike)MANBO_BEYOND_CORE.get());
        output.accept((ItemLike)MANBO_INVISABLE_CORE.get());
        output.accept((ItemLike)KINGS_SHADOW.get());
        output.accept((ItemLike)MANBO_FINAL_SWORD.get());
    }).build());
}

